### ISSUE TITLE
[镜像请求] 请求添加 ImmortalWrt 镜像

### ISSUE THREAD

**Issue by douglarek** [ShanghaitechGeekPie/shanghaitech-mirror-frontend#2]
### 先决条件 / Prerequisites

- [X] 该项目未在其他被标为 wontfix 的 [issues](https://github.com/ShanghaitechGeekPie/shanghaitech-mirror-frontend/issues) 中讨论过。
No previous issues with "wontfix" label have discussed about mirroring this project.

### 项目简介 / Introduction

ImmortalWrt 是 OpenWrt 的一个第三方分支，主要针对国人用户开发，提供更多的本地化软件包和设备支持。

项目地址： https://github.com/immortalwrt

### 上游地址与镜像方法 / Upstream & Method

下载地址： https://downloads.immortalwrt.org/

镜像方法：

```
env RSYNC_PASSWORD="immortalwrt-org" rsync -4ahv --delete-delay "rsync://firmwarepublic@rsync-mirror.infra.immortalwrt.org/firmware-public/" "immortalwrt/"
```

### 镜像大小 / Size

~560 GB

### 备注 / Notes

其他已通过镜像讨论：
* https://github.com/JLULUG/issues/issues/8
* https://github.com/sjtug/mirror-requests/issues/319

**Comment by Nyovelt** [comment]
@WAAutoMaton, take a look plz

**Comment by WAAutoMaton** [comment]
我们镜像站近期正在进行架构上的调整（期间可能出现无法访问等情况），因此不会进行内容修改。
我们将在调整完成后决定是否收录您的项目。

**Comment by wenxuanjun** [comment]
同步已经完成，见<https://mirrors.shanghaitech.edu.cn/immortalwrt/>，同步参数为`--exclude '/releases/*18.06*'`。该 issue 现将被关闭，如果您还有其他问题，可以继续在此留言。

**Comment by 1715173329** [comment]
Nice thanks!
